version: '3'

services:
  app:
    container_name: ansible_app_1
    image: mstf/ansible-node-app:v.0.1
    ports:
      - "127.0.0.1:3031:3031"
    environment:
      - PORT=3031
      - MONGO_LOCAL=mongodb://database:27017/task-manager
      - ACCESS_TOKEN=j23r0j239jr02h04tghh24g

  database:
    container_name: ansible_db_1
    image: mongo
    volumes:
      - ./data:/db/data

