---

- name: App folder and Downloads folder setup
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ app_root_dir }}"
    - "{{ download_dir }}"


- name: Copy docker files
  copy:
    src: "{{ item.filename }}"
    dest: "{{ app_root_dir }}"
    mode: 0644
  loop:
    - { filename: "Dockerfile" }
    - { filename: docker-compose.yaml }


- name: Download app from github
  git:
    repo: "{{ repo_address }}"
    dest: "{{ download_dir }}/Task-manager-app"
    update: yes
    force: yes


- name: Copy app files to correct dir
  copy:
    src: "{{ download_dir }}/Task-manager-app/"
    dest: "{{ app_root_dir }}"
    remote_src: yes


- name: Build app image - run Dockerfile
  docker_image:
    name: mstf/ansible-node-app
    tag: v.0.1
    source: build
    build:
      path: "{{ app_root_dir }}"


- name: Run docker-compose
  docker_compose:
    project_src: "{{ app_root_dir }}"
    state: present