---

- name: Docker and docker-compose installations
  apt:
    name: "{{ item.package }}"
    state: latest
  loop:
    - { package: docker.io }
    - { package: docker-compose }
  register: docker_install_response


- name: Restart OS to boot Docker
  reboot:
  async: 1
  poll: 0
  when: docker_install_response.changed == true


- name: Wait for OS reboot
  wait_for_connection:
    delay: 5
    timeout: 10
  when: docker_install_response.changed == true


- name: Start Docker
  systemd:
    name: docker
    state: started
    enabled: yes
